### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by fabiohxcx** [delay/flutter_starter#14]
Hi Jeff,

I am a Flutter enthusiast and have been studying a lot lately.

I liked very much this project sample and I'm using it as an example for me.

Especially the Loader that it can be called anywhere in the code.

But I notice a problem, despite the loading ignore touches due to Overlay, the physical back button on Android Devices still works. Therefore, during loading I may end up leaving the screen if I press back button.

I tried to use WillPopScore, but it didn't work.

Do you have any ideas to workaround it?

Thank you very much in advance

Fabio Hideki

**Comment by delay** [comment]
The loading indicator code is a modified and simplified version of this code.  https://github.com/fayaz07/ots You may want to look into that plugin as it has a lot of features that the code in this app does not have.
