### ISSUE TITLE
Possible to access translation labels without context?

### ISSUE THREAD

**Issue by JonathanRhein** [delay/flutter_starter#16]
Great tutorial on Medium!! Thanks a lot!

Is there a way to eliminate the necessity of passing `BuildContext` in 

`final labels = AppLocalizations.of(context);`

using **GetX**? I sometimes have to reference the _translation labels_ also in some of my controller/services classes where I usually try to avoid using `BuildContext` as much as possible (trying to separate UI and Business Logic).

**Comment by delay** [comment]
I actually no longer use AppLocalizations.of(context); in the current version.  I replaced the old translation component with doing it the getX way and I also created a new script to build the localization file.  You can take a look at the [readme](https://github.com/delay/flutter_starter#readme)  for how to use the new translation system.

**Comment by JonathanRhein** [comment]
Great - thank you! For some reason my compiler (Dart 2.12.3) complains about the `required` keyword in the constructors of `LocalizationModel` as well as `PhraseModel` in the `update_localizations.dart` file with the following message:

```
The parameter type 'dynamic' is incompatible with the field type 'String'.
Try changing or removing the parameter's type, or changing the field's type.dart(field_initializing_formal_not_assignable)
```

Once I remove the `required` keywords it is working fine :-)

**Comment by delay** [comment]
Ok are you using null safety in your project?  Maybe that is why as the required keyword is only used if you update your pubspec.yaml to use:
`environment:
  sdk: '>=2.12.0 <3.0.0' `

**Comment by JonathanRhein** [comment]
Ah, thank you for pointing that out! I have indeed not upgraded my project to null safety yet. Will be doing this in the future :-)
