### ISSUE TITLE
Update Profile Password Dialog

### ISSUE THREAD

**Issue by HussainON** [delay/flutter_starter#19]
Hi Jeff,

When you enter a wrong or empty password when trying to update profile info, the progress indicator keeps showing up and you no longer can press anything. I have to kill and rerun the code to work again.

**Comment by delay** [comment]
Thanks for the bug report, I was able to duplicate this error.  I will try to update this code at some point...  I will see what error messages I get back from firebase auth.  Thanks for reporting it.

**Comment by delay** [comment]
It should be fixed now... Thanks again for reporting the bug.
