### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by originalshop019** [delay/flutter_starter#23]
![issue](https://user-images.githubusercontent.com/63241839/121819914-aa9d0300-cc87-11eb-8e70-f5854349ae4f.jpg)

**Comment by originalshop019** [comment]
![app_debug_preview](https://user-images.githubusercontent.com/63241839/121820242-b4276a80-cc89-11eb-8a89-63bc687f0825.jpg)

**Comment by delay** [comment]
What were you doing when this error occurred?

**Comment by originalshop019** [comment]
nothing, this error occurred when i launch the app on device, i tried to fix it on home_ui in line 10 but nothing...i have added some users to my firestore but the error still showing up, 
I think probleme is in auth_controller too at snapshot.data()!...

**Comment by c0h1b4** [comment]
Same error here.

**Comment by jaquielajoie** [comment]
I have the same issue.

**The error occurs here**

Prior to adding admin, user collections to Firestore I was getting this error. Now the screen just is endlessly caught in a loading loop.

This problem arose after I switched the google-services.json file and changed your **com.example.app** to what mine needs to be.

I'm new to Flutter so I don't have any insights beyond this...

class HomeUI extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ......
      builder: (controller) => controller.firestoreUser.value?.uid  == null // Throws error if admin, users not in Firestore
         .......;
                      }),

**Comment by skobak** [comment]
Hey!
Thank you for an amazing starter.

Faced same issue, seems like firestoreUser not yet initialized during app launch. 
Do you know the solution?

Best

**Comment by delay** [comment]
Sorry guys I have been busy working on non-coding stuff for the last month or so.  I will try and take a look and see what is causing this trouble.  Thanks everyone for reporting this trouble.

**Comment by delay** [comment]
I am not able to duplicate this trouble.  I ran on ios, web and android and logged in with both admin and non admin users.  The only thing I can think of is did you setup your collections  and get your permissions correct?  If you are running for web you also need to update the index.html with your firebase config.

**Comment by delay** [comment]
Maybe double check your firebase config setup.  https://firebase.google.com/docs/flutter/setup?platform=android

**Comment by delay** [comment]
Closing this issue out for now.  So far I have not been able to duplicate it.
