### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by Astaxask** [delay/flutter_starter#28]
Hello Jeff,

Great project that I think is very helpful and time-saving for other devs. I have one question because it seems that when I have my google sheet and update the documentId and the sheetId and run the command line ``` dart update_localizations.dart ``` it works fine as seen below 

``` ruby
---------------------------------------
Downloading Google sheet url "https://docs.google.com/spreadsheets/d/1Ye9FMIJocRGBdOPk7CSo5obWlltcz2hPFiIn0B0P8ls/export?format=csv&id=1Ye9FMIJocRGBdOPk7CSo5obWlltcz2hPFiIn0B0P8ls&gid=0" ...
---------------------------------------

---------------------------------------
Saving localization.g.dart
---------------------------------------
Done...
```

But my file localizations.g.dart does not download the content in the google sheet

``` ruby
import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
            };
      }
```

It works fine when I use your google sheet document Id. Is it maybe that I need to do something with my google sheet? For example, make it public or download it somewhere else. Because it doesn’t seem that the code realizes there is content in my google sheet.

**Comment by delay** [comment]
Is your document viewable to all in the google sheet settings?
