### ISSUE TITLE
name can only contain letters

### ISSUE THREAD

**Issue by jtkeyva** [delay/flutter_starter#6]
cool start for a starter! when signing up, if you choose your name to be like elon musk's child and put a number in it, you get a validation error

**Comment by delay** [comment]
Yeah you can make the name validation anything you want.  Currently I don't allow numbers in names, but if you want just make a new validation method for the name.  You could even just change it to not allow a blank name if you want.  I have no plans to make the default method any less stringent.

**Comment by delay** [comment]
https://github.com/delay/flutter_starter/blob/master/lib/helpers/validator.dart

Change from name validator to notEmpty

**Comment by jtkeyva** [comment]
@delay awesome thanks! oh ya, any plans to add file uploads and/or make this starter under MIT license? GetX seems super powerful almost like "Vue for Flutter" and feel a starter using GetX would be used by many :)

**Comment by delay** [comment]
Added the MIT license.  I have no plans for file uploads but you certainly could add your own code for that.

**Comment by jtkeyva** [comment]
@delay very generous to open source it, hopefully the community gets a great start with your creation :)
