### ISSUE TITLE
ever(firebaseUser, handleAuthChanged) fires non-stop

### ISSUE THREAD

**Issue by psenechal** [delay/flutter_starter#9]
Authentication was working perfectly fine until I decided to update Android Studio, Flutter, and dependencies.

All of a sudden, the ever(firebaseUser, handleAuthChanged) in auth_controller now fires non-stop when a user logs in. Eventually Firebase will not allow any additional queries due to hitting the quota limit and the app crashes.
I tried rolling back the dependencies to when this was working, but it didn't help, which leads me to believe it's something that has changed in Flutter or Dart.

[✓] Flutter (Channel master, 1.24.0-8.0.pre.236, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

  firebase_auth: 0.18.3
  firebase_core: 0.5.2

Would you by chance have any idea why this is happening? I can't seem to figure it out. Thanks!

**Comment by psenechal** [comment]
I got it figured out. The problem is actually a change in Get. The current code in your project is
```
  @override
  void onReady() async {
    //run every time auth state changes
    ever(firebaseUser, handleAuthChanged);
    firebaseUser.value = await getUser;
    firebaseUser.bindStream(user);
    super.onInit();
  }
```

changing it to
```
  @override
  void onReady() async {
    //run every time auth state changes
    ever(firebaseUser, handleAuthChanged);
    firebaseUser.value = await getUser;
    firebaseUser.bindStream(user);
    super.onReady();
  }
```

appears to have solved the issue. Must have been some change with the way Get checks overrides now.

**Comment by delay** [comment]
Thanks so much for the fix! I will update my code.
